-- liquibase formatted sql
-- changeset vishal:1675168348498-1
CREATE TABLE FAX_OUTBOUND_DETAIL (
  id INT AUTO_INCREMENT NOT NULL,
  PARTNER_ID INT NOT NULL,
  APPOINTMENT_ID INT NULL,
  PATIENT_ID INT NULL,
  SENDER_FAX_NUMBER VARCHAR(30) NULL,
  FAX_TEMPLATE_TYPE ENUM('APPOINTMENT_BOOKING') NOT NULL,
  RECIPIENT_FAX_NUMBER VARCHAR(30) NOT NULL,
  FAX_SEND_STATUS ENUM('FAIL', 'SUCCESS', 'PROCESSING') NOT NULL,
  FAX_SEND_ERROR LONGTEXT NULL,
  CREATED_AT datetime DEFAULT NOW() NOT NULL,
  UPDATED_AT datetime DEFAULT NOW() NOT NULL,
  FAX_PROVIDER ENUM('OTHER', 'UNITE_FAX', 'RING_CENTRAL', 'SRFAX') DEFAULT 'OTHER' NOT NULL,
  REFERRAL_ID INT NULL,
  CONSTRAINT PK_FAX_OUTBOUND_DETAIL PRIMARY KEY (id)
);