--liquibase formatted sql
--changeset souvik:v1.0.9_PHPROJ-1359_Column_Population
 
ALTER TABLE `FAX_DETAIL` CHANGE `DOCUMENT_TYPE` `DOCUMENT_TYPE` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;

ALTER TABLE `FAX_DETAIL` ADD `PATIENT_NAME` VARCHAR(250) NULL DEFAULT NULL, ADD INDEX (`PATIENT_NAME`);

ALTER TABLE `FAX_DETAIL` ADD `PATIENT_MATCH_STATUS` ENUM('MULTIPLE', 'SINGLE', 'NONE') NULL DEFAULT NULL, ADD INDEX (`PATIENT_MATCH_STATUS`);

ALTER TABLE `FAX_DETAIL` ADD `PRIORITY` VARCHAR(250) NULL DEFAULT NULL;

ALTER TABLE `FAX_DETAIL` ADD `FROM_USER` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `FAX_DETAIL` ADD INDEX(`PARTNER_ID`);

ALTER TABLE `FAX_DETAIL` ADD INDEX(`PDF_Document_Id`);

ALTER TABLE `FAX_DETAIL` ADD INDEX(`Tif_Document_Id`);

--rollback DROP TABLE FAX_DETAIL