-- liquibase formatted sql
-- changeset ravi:16751684548596-1
ALTER TABLE `FAX_OUTBOUND_DETAIL` CHANGE `FAX_TEMPLATE_TYPE` `FAX_TEMPLATE_TYPE` ENUM('APPOINTMENT_BOOKING','MISSING_ITEM','REFERRAL_RECEIVED') NOT NULL;
